
email_qq:
  name: QQ
  host: smtp.qq.com
  user: 1365810824@qq.com
  pass: fhakgreinnkmbaea
  recipients: 997154440@qq.com
  subject: Ecshop手机版测试报告
  part: 测试的正文部分


email_wechat:
  name: Whect
  host: smtp.exmail.qq.com
  user: wangqitao@aomeikeji.com
  pass: bdhepFnqqjxT8P3G
  recipients: yangtao@aomeikeji.com
  subject: Ecshop手机版测试报告
  part: 测试的正文部分








